version: '3.8'

services:
  nexus-next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-next-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
